/*
 * MUART_Config.h
 *
 *  Created on: Nov 25, 2022
 *      Author: Ismail
 */

#ifndef MCAL_MUSART_MUSART_CONFIG_H_
#define MCAL_MUSART_MUSART_CONFIG_H_

/*OPTIONS FOR OPERATING MODE
 *
 * 1-MUSART_SYNCHRONOUS_MODE
 * 2-MUSART_ASYNCHRONOUS_MODE
 *
 *
 * */
#define MUSART_OPERATING_MODE MUSART_ASYNCHRONOUS_MODE
/*options for parity bit check
 *
 * MUSART_PARITY_DISABLED
 * MUSART_PARITY_ODD
 * MUSART_PARITY_EVEN
 */
#define MUSART_PARITY_MODE MUSART_PARITY_EVEN
/*OPTIONS FOR STOP BITS
 * MUSART_ONE_STOP_BIT
 * MUSART_TWO_STOP_BIT
 */
#define MUSART_STOP_MODE MUSART_ONE_STOP_BIT
/*OPTIONS FOR DATA_BITS
 * MUSART_FIVE_DATA_BITS
 * MUSART_SIX_DATA_BITS
 * MUSART_SEVEN_DATA_BITS
 * MUSART_EIGHT_DATA_BITS
 * MUSART_NINE_DATA_BITS
 */
#define MUSART_DATA_SIZE MUSART_EIGHT_DATA_BITS
/*OPTIONS FOR BAUD_RATE
 * MUSART_2400
 * MUSART_4800
 * MUSART_9600
 * MUSART_19200
 * MUSART_38400
 */
#define MUSART_BAUD_RATE  MUSART_9600


#endif /* MCAL_MUSART_MUSART_CONFIG_H_ */
