/*
 * MTWI_Config.h
 *
 *  Created on: Dec 2, 2022
 *      Author: Ismail
 */

#ifndef MCAL_MTWI_MTWI_CONFIG_H_
#define MCAL_MTWI_MTWI_CONFIG_H_

/*OPTIONS FOR INTERUPTS:
 * 1-MTWI_INTERUPT_DISABLED
 * 2-MTWI_INTERUPT_ENABLED
 * */
#define MTWI_INTERUPT_MODE MTWI_INTERUPT_DISABLED
/*options for prescaler
 * 1-MTWI_PRESCALER_BY_1
 * 2-MTWI_PRESCALER_BY_4
 * 3-MTWI_PRESCALER_BY_16
 * 4-MTWI_PRESCALER_BY_64
 *
 */
#define MTWI_PRESCALER_MODE MTWI_PRESCALER_BY_1

#endif /* MCAL_MTWI_MTWI_CONFIG_H_ */
